In [ ]:
arr = np.array[[[4,2,3],
                [8,6,9]]
                [[6,7,8],
                 [2,1,3]]]
arr

arr.size    #works like len
arr.shape   #shows how many elements and whats the matrix dimension of each

3 dimensional array is an array of 2-dimensional elements.. so on and so forth
3 dimensional array can have a single element as well

arr5 = np.array[[[3,4,5,6]]]
arr5.shape will be 1,1,4

3 dimensions and more are called tensors

arr.dtype will show the type of the array
arrays are homogenous,

np.arange(optional start, stop, step, dtype=)
this by default creates 1 dimensional array

np.arange(20).reshape(5,4)
this way you can reshape into two dimensions. the dimensionality number is based on number of elements

np.arange(30).reshape(3,2,5) for 3 dimensions and so on



In [1]:
import numpy as np

In [29]:
x = np.array([[1, 2, 3], [3, 4,9]])
y = np.array([[5, 6, 7], [15, 61, 79]])

In [30]:
print(x.size)
print(y.size)

6
6


In [34]:
z1 = np.concatenate((x,y))
z2 = np.concatenate((x,y), axis=0)
z3 = np.concatenate((x,y), axis=1)
print("z1==>", z1, "shape: ", z1.shape, "dim: ", z1.ndim)
print("z2==>", z2, "shape: ", z2.shape, "dim: ", z2.ndim)
print("z3==>", z3, "shape: ", z3.shape, "dim: ", z3.ndim)

z1==> [[ 1  2  3]
 [ 3  4  9]
 [ 5  6  7]
 [15 61 79]] shape:  (4, 3) dim:  2
z2==> [[ 1  2  3]
 [ 3  4  9]
 [ 5  6  7]
 [15 61 79]] shape:  (4, 3) dim:  2
z3==> [[ 1  2  3  5  6  7]
 [ 3  4  9 15 61 79]] shape:  (2, 6) dim:  2


In [36]:
z3.reshape(3,4)

array([[ 1,  2,  3,  5],
       [ 6,  7,  3,  4],
       [ 9, 15, 61, 79]])